# Generated by Django 4.0.2 on 2022-02-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='article',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.TextField(max_length=2000, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=200, verbose_name='Вопрос'),
        ),
    ]
